// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNKAVkPomvkcVy8Kh_FgQ8LZKHKE-_DkU',
    appId: '1:602773727145:web:a81245f86a1a4b7851c6b8',
    messagingSenderId: '602773727145',
    projectId: 'thisisthelast-34f53',
    authDomain: 'thisisthelast-34f53.firebaseapp.com',
    storageBucket: 'thisisthelast-34f53.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3__q77j3EdLELqfUtLSUlNW9R4mIk8-0',
    appId: '1:602773727145:android:e089e9fb1359e4ef51c6b8',
    messagingSenderId: '602773727145',
    projectId: 'thisisthelast-34f53',
    storageBucket: 'thisisthelast-34f53.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNKAVkPomvkcVy8Kh_FgQ8LZKHKE-_DkU',
    appId: '1:602773727145:web:94c4bb8f0284f70e51c6b8',
    messagingSenderId: '602773727145',
    projectId: 'thisisthelast-34f53',
    authDomain: 'thisisthelast-34f53.firebaseapp.com',
    storageBucket: 'thisisthelast-34f53.firebasestorage.app',
  );
}
